volumes:
  mysql-data:
networks:
  spring-boot-mysql-network:
    name: spring-boot-mysql-network
services:
  mysqldb:
    image: mysql:lts

    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=project_apply
      - MYSQL_ROOT_PASSWORD=rootroot
    networks:
      - spring-boot-mysql-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 60s
      retries: 10
  stockmeatsolutions:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: Project-Apply

      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/project_apply?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

      SPRING_MAIL_HOST: smtp-relay.brevo.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

      SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}

    networks:
      - spring-boot-mysql-network
